USE quizmedb;

DROP TABLE UserHasFollowingList;
DROP TABLE CommentsHasLikesList;
DROP TABLE ReviewsHasComments;
DROP TABLE ReviewsHasLikesList;
DROP TABLE UserWritesReviews;
DROP TABLE SetsHasReviews;
DROP TABLE Reviews;
DROP TABLE SetHasFlashcards;
DROP TABLE FrontHasBack;
DROP TABLE Flashcards;
DROP TABLE SetHasTag;
DROP TABLE Tag;
DROP TABLE FolderHasSets;
DROP TABLE UserCreatesSets;
DROP TABLE Sets;
DROP TABLE UsersCreatesFolder;
DROP TABLE Folder;
DROP TABLE Users;